#!/bin/bash

FRAMEWORK_VERSION="1.4-RELEASE"

if [ -z "$JAVA_HOME" ]; then
    echo "Please insert JDK 8 home directory: "
    read APPLICAFRAMEWORK_HOME
fi

if [ -z "$APPLICAFRAMEWORK_HOME" ]; then
    echo "Please insert Applica framework home directory: "
    read APPLICAFRAMEWORK_HOME
fi

JAVA="$JAVA_HOME/bin/java"
JAR="${APPLICAFRAMEWORK_HOME}/scripts/target/scripts-$FRAMEWORK_VERSION.jar"
$JAVA -classpath "${APPLICAFRAMEWORK_HOME}/scripts/target/lib/*:$JAR" applica.framework.Applica $@
